// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoID39l-eHij_1aEohFiMPSTDy_4GH7aI',
    appId: '1:99744875642:web:e7e78ccbf67cfa755d67c3',
    messagingSenderId: '99744875642',
    projectId: 'isobit-1e4c5',
    authDomain: 'isobit-1e4c5.firebaseapp.com',
    databaseURL: 'https://isobit-1e4c5.firebaseio.com',
    storageBucket: 'isobit-1e4c5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7ZAZAAmj9NSfxD5i9a_ZYeNujefD4ARw',
    appId: '1:99744875642:android:644e420e7131d8a85d67c3',
    messagingSenderId: '99744875642',
    projectId: 'isobit-1e4c5',
    databaseURL: 'https://isobit-1e4c5.firebaseio.com',
    storageBucket: 'isobit-1e4c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlbHf1GdcEfOXMgUs4wC8Yr2pE9c9izyw',
    appId: '1:99744875642:ios:b61efae03f5a85a15d67c3',
    messagingSenderId: '99744875642',
    projectId: 'isobit-1e4c5',
    databaseURL: 'https://isobit-1e4c5.firebaseio.com',
    storageBucket: 'isobit-1e4c5.appspot.com',
    iosClientId: '99744875642-v6ld1ks9ar017ltgtm6uflpr3rhmhfm9.apps.googleusercontent.com',
    iosBundleId: 'com.etechviral.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlbHf1GdcEfOXMgUs4wC8Yr2pE9c9izyw',
    appId: '1:99744875642:ios:ffe73a82600379925d67c3',
    messagingSenderId: '99744875642',
    projectId: 'isobit-1e4c5',
    databaseURL: 'https://isobit-1e4c5.firebaseio.com',
    storageBucket: 'isobit-1e4c5.appspot.com',
    iosClientId: '99744875642-vujrg5tj13kiug6uuqtoc4qhhqtpi5ds.apps.googleusercontent.com',
    iosBundleId: 'com.etechviral.notesApp.RunnerTests',
  );
}
