name: flutter_application_1

dependencies:
  http: '0.11.3+17'
  flutter:
    sdk: flutter
  intl: ^0.15.8



  flutter_screenutil: ^0.5.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
