name: Build and deploy Flutter Web

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: flutter-web-production
  cancel-in-progress: true

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v6

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Mostrar versión de Flutter
        run: flutter --version

      - name: Instalar dependencias
        run: flutter pub get

      #- name: Analizar proyecto
      #  run: flutter analyze --no-fatal-infos

      - name: Compilar Flutter Web
        run: >
          flutter build web
          --release
        #.--base-href /flutter_erp/

      - name: Desplegar por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: build/web/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          dangerous-clean-slate: false